version: "3"
services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "${POSTGRES_USER_NAME}"
      POSTGRES_PASSWORD: "${POSTGRES_USER_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DATABASE_NAME}"
    volumes:
      - "${POSTGRES_DATA}:${POSTGRES_CONTAINER_DATA}"
  redis:
    image: redis:latest
    ports:
      - 6379:6379
