[package]
name = "telemetries"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.1"
tracing = "0.1"
tracing-bunyan-formatter = "0.3"
tracing-log = "0.1"
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter"] }
